// Self-contained API client for the mobile app.
//
// This app is intentionally standalone — it does NOT depend on the monorepo's
// shared packages (@ucpt/sdk, @ucpt/types, @ucpt/validation) so it can be lifted
// into its own repository as-is. The thin fetch wrapper below mirrors the shared
// SDK's contract (a `request` over `<baseUrl>/api/v1`), the Bearer token is read
// from SecureStore, and the base URL is resolved for both simulator and device.
import * as SecureStore from 'expo-secure-store';
import Constants from 'expo-constants';

const DEV_API_PORT = 4000;

/** Error payload shape the backend returns on failures. */
export interface ApiError {
  error: string;
  code?: string;
}

/** Thrown for any non-2xx API response, carrying the HTTP status + payload. */
export class ApiClientError extends Error {
  constructor(
    public status: number,
    public payload: ApiError,
  ) {
    super(payload?.error ?? 'Request failed');
    this.name = 'ApiClientError';
  }
}

/**
 * Resolve the backend base URL.
 *
 * On a physical device (Expo Go), `localhost` points at the phone, not the Mac
 * running the backend — so a hard-coded `http://localhost:4000` fails with
 * "Can't reach the server" even though it works in the simulator. In dev we
 * instead reuse the LAN IP Expo is already serving Metro from (e.g.
 * `192.168.18.43:8081`) and swap in the API port, so the same code works on
 * both the simulator and a real device with no manual config. A non-localhost
 * URL (e.g. a deployed API) is always used verbatim.
 */
function resolveBaseUrl(): string {
  const explicit =
    process.env.EXPO_PUBLIC_API_BASE_URL ??
    (Constants.expoConfig?.extra?.apiBaseUrl as string | undefined);
  const configured = explicit?.trim();

  const hostUri =
    Constants.expoConfig?.hostUri ??
    (Constants as unknown as { debuggerHost?: string }).debuggerHost;
  const lanHost = hostUri?.split(':')[0];

  if (configured) {
    if (lanHost && /^https?:\/\/(localhost|127\.0\.0\.1)/i.test(configured)) {
      return configured.replace(/\/\/(localhost|127\.0\.0\.1)(:\d+)?/i, `//${lanHost}:${DEV_API_PORT}`);
    }
    return configured;
  }

  return lanHost ? `http://${lanHost}:${DEV_API_PORT}` : `http://localhost:${DEV_API_PORT}`;
}

export const API_BASE_URL = resolveBaseUrl();

const base = API_BASE_URL.replace(/\/$/, '');

// A short-lived access token expires (~15 min). On a 401 we rotate it once using
// the stored refresh token, then retry — so the user isn't logged out mid-session.
let refreshing: Promise<boolean> | null = null;

async function tryRefresh(): Promise<boolean> {
  const refreshToken = await SecureStore.getItemAsync('refreshToken');
  if (!refreshToken) return false;
  if (!refreshing) {
    refreshing = (async () => {
      try {
        const res = await fetch(`${base}/api/v1/auth/refresh`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ refreshToken }),
        });
        if (!res.ok) return false;
        const data = (await res.json()) as { accessToken?: string; refreshToken?: string };
        if (data.accessToken && data.refreshToken) {
          await SecureStore.setItemAsync('accessToken', data.accessToken);
          await SecureStore.setItemAsync('refreshToken', data.refreshToken);
          return true;
        }
        return false;
      } catch {
        return false;
      } finally {
        refreshing = null;
      }
    })();
  }
  return refreshing;
}

async function request<T>(
  method: string,
  path: string,
  body?: unknown,
  init?: RequestInit,
  _retried = false,
): Promise<T> {
  const token = (await SecureStore.getItemAsync('accessToken')) ?? undefined;
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
    ...(token ? { Authorization: `Bearer ${token}` } : {}),
    ...((init?.headers as Record<string, string>) ?? {}),
  };
  const res = await fetch(`${base}/api/v1${path}`, {
    ...init,
    method,
    headers,
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  const text = await res.text();
  const json = text ? JSON.parse(text) : undefined;
  if (!res.ok) {
    // Expired access token → refresh once and retry (never for the auth endpoints
    // themselves, where a 401 is a genuine bad-credentials error).
    if (res.status === 401 && !_retried && !path.startsWith('/auth/')) {
      if (await tryRefresh()) return request<T>(method, path, body, init, true);
    }
    throw new ApiClientError(res.status, (json as ApiError) ?? { error: 'Request failed' });
  }
  return json as T;
}

/**
 * Multipart upload of ONE local file (a photo picked from the library/camera, or a
 * document). Kept separate from `request` because that JSON-encodes its body — here the
 * body must be a FormData and the `multipart/form-data` boundary has to be generated by
 * fetch itself, so the Content-Type header is deliberately NOT set.
 *
 * React Native's FormData accepts `{ uri, name, type }` in place of a Blob, which is how
 * a local `file://` URI gets streamed without reading it into memory first.
 */
async function upload<T>(
  path: string,
  file: { uri: string; name: string; type: string },
  field = 'file',
  _retried = false,
): Promise<T> {
  const token = (await SecureStore.getItemAsync('accessToken')) ?? undefined;
  const form = new FormData();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  form.append(field, file as any);

  const res = await fetch(`${base}/api/v1${path}`, {
    method: 'POST',
    headers: token ? { Authorization: `Bearer ${token}` } : undefined,
    body: form,
  });
  const text = await res.text();
  const json = text ? JSON.parse(text) : undefined;
  if (!res.ok) {
    if (res.status === 401 && !_retried) {
      if (await tryRefresh()) return upload<T>(path, file, field, true);
    }
    throw new ApiClientError(res.status, (json as ApiError) ?? { error: 'Upload failed' });
  }
  return json as T;
}

/** Shared client used by every module in this folder. */
export const api = { request, upload };
